version: '3.0'

services:
    website-nginx-proxy:
        image: nginxproxy/nginx-proxy
        container_name:  website-nginx-proxy
        networks:
            - website-network
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx_proxy_conf:/etc/nginx/conf.d
        environment:
            - DEFAULT_HOST=huyenduc.click
            - VIRTUAL_PROTO=http

    website-database:
        image: mysql:8.0.33
        container_name: website-database
        restart: always
        networks:
            - website-network
        volumes:
            - data:/var/lib/mysql
            - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306
volumes:
    data:
    
networks:
    website-network:
        driver: bridge
        name: website-network