name: Deloy to server

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
            file: ./src/Website.Api/Dockerfile

        - name: Connect to VPS and run docker compose
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.HOST_IP }}
            username: ${{ secrets.HOST_USERNAME }}
            password: ${{ secrets.HOST_PASSWORD }}
            script: |

              if [ ! -d ~/website-core ]; then
                mkdir ~/website-core
              fi

              if [[ -f website-core/.env ]]; then
                sed -i 's/^MYSQL_SERVER=.*/MYSQL_SERVER=${{ secrets.MYSQL_SERVER }}/' ~/website-core/.env
                sed -i 's/^MYSQL_ROOT_USER=.*/MYSQL_ROOT_USER=${{ secrets.MYSQL_ROOT_USER }}/' ~/website-core/.env
                sed -i 's/^MYSQL_ROOT_PASSWORD=.*/MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}/' ~/website-core/.env
                sed -i 's/^MYSQL_USER=.*/MYSQL_USER=${{ secrets.MYSQL_USER }}/' ~/website-core/.env
                sed -i 's/^MYSQL_PASSWORD=.*/MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}/' ~/website-core/.env
                sed -i 's/^MYSQL_DATABASE=.*/MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}/' ~/website-core/.env
              else
                echo "MYSQL_SERVER=${{ secrets.MYSQL_SERVER }}" > website-core/.env
                echo "MYSQL_ROOT_USER=${{ secrets.MYSQL_ROOT_USER }}" >> website-core/.env
                echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> website-core/.env
                echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> website-core/.env
                echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> website-core/.env
                echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> website-core/.env
              fi
            
              cd ~/website-core/

              docker compose up -d
                      
        - name: Send telegram message on push
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              ${{ github.actor }} created commit:
              Commit message: ${{ github.event.commits[0].message }}
              
              Repository: ${{ github.repository }}
              
              Commit: https://github.com/${{ github.repository }}/commit/${{github.sha}}

              